version: '3.9'
services:
  api:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    ports:
      - '8000:8000'
    environment:
      - MODULES_SCREENSNAP=true
      - MODULES_LLM_INSIGHTS=true
      - LLM_BASE_URL=http://localhost:11434/v1
      - LLM_MODEL=gpt-4o-mini
  web:
    build:
      context: .
      dockerfile: docker/web.Dockerfile
    environment:
      - VITE_API_URL=http://api:8000
    ports:
      - '5173:5173'
    depends_on:
      - api
    command: npm run dev -- --host 0.0.0.0 --port 5173
