version: '3.9'
services:
  api:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    ports:
      - '8000:8000'
  web:
    build:
      context: .
      dockerfile: docker/web.Dockerfile
    environment:
      - VITE_API_URL=http://api:8000
    ports:
      - '5173:5173'
    depends_on:
      - api
    command: npm run dev -- --host 0.0.0.0 --port 5173
